;this file for FamiTone5.1 library generated by text2vol5 tool
;edited by Doug Fraker, 2025, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


sfx_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; New song

@instruments:
	.word @env1,@env0,@env0,@env0
	.word @env1,@env2,@env3,@env4

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $c0,$c2,$c4,$bf,$c0,$00,$04
@env3:
	.byte $c0,$c9,$c0,$c0,$00,$03
@env4:
	.byte $c2,$00,$00


; New song
@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $7f,$68,$80,$2d,$7c,$67,$81,$7a,$65,$81,$78,$63,$81,$77,$61,$81
	.byte $74,$6d,$44,$81,$70,$00,$f1
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref1:
	.byte $f9,$85
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref2:
	.byte $f9,$85
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref3:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref4:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
