;this file for FamiTone5.1 library generated by text2vol5 tool
;edited by Doug Fraker, 2025, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


songs_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Title Theme
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256 ; The Depths

@instruments:
	.word @env1,@env0,@env0,@env0
	.word @env2,@env0,@env0,@env5
	.word @env3,@env0,@env0,@env6
	.word @env4,@env0,@env0,@env7
	.word @env1,@env0,@env0,@env6

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $c5,$c9,$cf,$00,$02
@env3:
	.byte $c1,$c7,$ce,$cf,$00,$03
@env4:
	.byte $c3,$c7,$cb,$cf,$00,$03
@env5:
	.byte $c2,$00,$00
@env6:
	.byte $c1,$00,$00
@env7:
	.byte $c1,$c2,$c2,$c3,$00,$03


; Title Theme
@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $6d,$15,$86,$28,$8d,$5f,$20,$95,$61,$23,$95,$60,$2a,$8d,$1e,$83
	.byte $62,$81,$6f,$12,$20,$83,$6f,$00,$81,$60,$87,$23,$95
	.byte $fd
	.word @song0ch0loop

; Title Theme
@song0ch1:
@song0ch1loop:
@ref1:
	.byte $6d,$15,$87,$86,$23,$85,$5f,$8f,$61,$28,$8d,$20,$95,$60,$23,$95
	.byte $61,$20,$8d,$60,$1e,$8d
	.byte $fd
	.word @song0ch1loop

; Title Theme
@song0ch2:
@song0ch2loop:
@ref2:
	.byte $f9,$85
	.byte $fd
	.word @song0ch2loop

; Title Theme
@song0ch3:
@song0ch3loop:
@ref3:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

; Title Theme
@song0ch4:
@song0ch4loop:
@ref4:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop


; The Depths
@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref5:
	.byte $86,$28,$8d,$88,$2a,$8d,$86,$28,$85,$88,$27,$87,$7a,$6d,$11,$86
	.byte $28,$8b
@ref6:
	.byte $85,$7f,$60,$88,$27,$8d,$86,$25,$93,$77,$88,$23,$85,$7f,$86,$23
	.byte $89
@ref7:
	.byte $70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81
	.byte $70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81
	.byte $70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81
	.byte $70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81,$70,$81
	.byte $ff,$20
	.word @ref7
	.byte $fd
	.word @song1ch0loop

; The Depths
@song1ch1:
@song1ch1loop:
@ref9:
	.byte $86,$23,$ad,$61,$81,$61,$81,$61,$8b
@ref10:
	.byte $85,$60,$8f,$21,$9b,$20,$89
	.byte $ff,$20
	.word @ref7
	.byte $ff,$20
	.word @ref7
	.byte $fd
	.word @song1ch1loop

; The Depths
@song1ch2:
@song1ch2loop:
@ref13:
	.byte $86,$20,$ad,$66,$82,$1e,$8d
@ref14:
	.byte $83,$81,$60,$8f,$84,$1e,$a7
@ref15:
	.byte $81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81
	.byte $81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81,$81
	.byte $ff,$20
	.word @ref15
	.byte $fd
	.word @song1ch2loop

; The Depths
@song1ch3:
@song1ch3loop:
@ref17:
	.byte $bf
@ref18:
	.byte $bf
	.byte $ff,$20
	.word @ref7
	.byte $ff,$20
	.word @ref7
	.byte $fd
	.word @song1ch3loop

; The Depths
@song1ch4:
@song1ch4loop:
@ref21:
	.byte $bf
@ref22:
	.byte $bf
	.byte $ff,$20
	.word @ref15
	.byte $ff,$20
	.word @ref15
	.byte $fd
	.word @song1ch4loop
